# Site settings
title: Seera Networks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: eyedivision
github_username:  eye-division

# Build settings
markdown: kramdown

# Pretty URL
permalink: "posts/:title"

# Collections
collections:
  partners:
    output: true
  categories:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

sass:
    style: :compressed
